language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jt10/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jt10/docker-react npm run test


